Ommit display of blank body lines
maiha/pcap.cr pull request #3
Opened 2016-09-14 03:27 UTC by puppetpies

When developing my WIre tool i discovered in body mode that there are blank lines which are a size of 2.

I was thinking maybe implement it in library however feels wrong at the lower level.

This isn't really a pull request its whatever you make / choose todo but for my tool i don't want blank lines in my database.

Just thought i would make you aware of it !

Regards,

Brian

2016-09-14 09:30 UTC, maiha commented
Hi, Brian!

> however feels wrong at the lower level

It should be I think :)

> i don't want blank lines in my database

I agree with your use case, but ignoring blank lines sometimes breaks other cases.
For example, I can image the case of monitoring ping messages that send some white spaces.

So, why don't you add a new option to control the behavior? I love the explicit way like that.
Well, candidates are ...

- "-w" : we can easily image White spaces ( `diff(1)` uses this as `ignore all white space`)

Thought?

2016-09-15 15:04 UTC, maiha commented on examples/tcpsniffer.cr
> +  parser.on("-w", "We can easily manage White spaces ( diff(1) uses this as ignore all white space)") { whitespace = true }
Oh, that message was a comment for you :)
Please write like this for the description.
`"Ignore all packets that contain only white spaces"`

2016-09-15 15:07 UTC, maiha commented on examples/tcpsniffer.cr
> +      if whitespace
imaged just skip the case of blank packets like this.
```
     if bodymode
+      next if whitespace && pkt.tcp_data.to_s =~ /\A\s*\Z/
       puts "%s: %s" % [pkt.packet_header, pkt.tcp_data.to_s.inspect]
```

2016-09-15 15:08 UTC, maiha requested changes

2016-09-15 22:53 UTC, puppetpies commented on examples/tcpsniffer.cr
> +      if whitespace
I like it will change shortly !

2016-09-15 23:03 UTC, puppetpies commented
Ok code now in place !

2016-09-15 23:16 UTC, puppetpies commented
Also removed constant as no longer required !

2016-09-16 01:29 UTC, maiha approved these changes

2016-09-16 01:32 UTC, maiha commented
Ok, it seems nice hack! I'll merge this ASAP.
Could you merge these 5 commits into 1 commit?

2016-09-16 23:58 UTC, puppetpies commented
I will close this now open new thread !

2016-09-16 23:58 UTC, closed without merging

2016-09-21 18:16 UTC, maiha commented
FYI @puppetpies:

> I was thinking maybe implement it in library however feels wrong at the lower level.

Found this problem, and fixed the bug!
https://github.com/maiha/pcap.cr/commit/a1307f7970d183880b5f43020d22b81293210ae7

Regards,
maiha